apiVersion: v1
kind: Service
metadata:
   name: test-service
spec:
   ports:
   -  port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
   type: NodePort
   selector:
      app: nginx
