apiVersion: v1
kind: Service
metadata:
   name: nginx-service
   labels:
      name: nginx-deployment
spec:
   ports:
   -  port: 80
      targetPort: 80
      protocol: TCP
   loadBalancerIP: your-static-ip # 行ごと削除して指定しなければ自動でエフェメラルIPが付与される
   type: LoadBalancer
   selector:
      app: nginx
