apiVersion: v1
kind: Service
metadata:
   name: test-service
   labels:
      name: test-deployment
spec:
   ports:
   -  port: 80
      targetPort: 80
      protocol: TCP
   type: LoadBalancer
   selector:
      app: nginx
